/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.Iterator;
import java.util.Map;
import java.util.Set;

import javax.swing.DefaultListModel;

import dao.JDBCTester;

/**
 *
 * @author zwd
 */
public class TestJFrame extends javax.swing.JFrame {
    
    private final DefaultListModel<String> dlm = new DefaultListModel();
    public static MySQLDao mysqldao = new MySQLDao();
    private static int listindex = 0;
    private CrawlTool ctool = new CrawlTool();

    /**
     * Creates new form TestJFrame
     */
    public TestJFrame() {
        
        String[] listitems = {"该列表控件将显示如下信息：", "1.结果信息；", 
                                    "2.测试信息"};
        dlm.add(listindex++, listitems[0]);
        dlm.add(listindex++, listitems[1]);
        dlm.add(listindex++, listitems[2]);
//        scholarradiobutton.setSelected(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        woshost = new javax.swing.JLabel();
        scholarhost = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dbhost = new javax.swing.JLabel();
        dbusername = new javax.swing.JLabel();
        dbpassword = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        wosradiobutton = new javax.swing.JRadioButton();
        scholarradiobutton = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        woshost.setText("WOSHost");

        scholarhost.setText("ScholarHost");

        jTextField1.setText("http://apps.webofknowledge.com/");

        jTextField2.setText("http://scholar.google.com/");

        jButton1.setText("测试WOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryWOS(evt);
            }
        });

        jButton2.setText("测试Scholar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryScholarGoogle(evt);
            }
        });

        dbhost.setText("DB Host");

        dbusername.setText("UserName");

        dbpassword.setText("Password");

        jTextField3.setText("127.0.0.1");

        jTextField4.setText("jzus");

        jButton3.setText("测试数据连接");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryDBConnection(evt);
            }
        });

        wosradiobutton.setSelected(true);
        wosradiobutton.setText("抓取WOS引用数");
        wosradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wosradiobuttonActionPerformed(evt);
            }
        });

        scholarradiobutton.setText("抓取Scholar.google引用数");
        scholarradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scholarradiobuttonActionPerformed(evt);
            }
        });

        jButton4.setText("停止");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopCrawlCitation(evt);
            }
        });

        jButton5.setText("开始");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCrawlCitation(evt);
            }
        });

        jList1.setModel(dlm);
        jScrollPane1.setViewportView(jList1);

        jButton6.setText("获取文献数据");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getLiterInfo(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(scholarhost)
                                .addComponent(woshost, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(dbhost))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbpassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dbusername, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jPasswordField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wosradiobutton)
                            .addComponent(scholarradiobutton))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(woshost)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scholarhost)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dbhost)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dbusername)
                            .addComponent(jTextField4)
                            .addComponent(jButton3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(dbpassword))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPasswordField1)
                                    .addComponent(jButton6))
                                .addGap(4, 4, 4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton5))
                            .addComponent(wosradiobutton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scholarradiobutton)
                            .addComponent(jButton4))
                        .addGap(177, 177, 177)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>                        

    private void tryWOS(java.awt.event.ActionEvent evt) {
    	String woshost = jTextField1.getText();
    	if (ctool.tryWOS(woshost)) {
            dlm.insertElementAt("SUCCESS:web of science可以访问", 0);
    	} else {
    		dlm.insertElementAt("FAILED:web of science不能访问，请先连接RVPN", 0);
    	}
        //jList1.setModel(dlm);
    }                       

    private void tryScholarGoogle(java.awt.event.ActionEvent evt) {
    	String scholarhost = jTextField2.getText();
    	if (ctool.tryScholar(scholarhost)) {
            dlm.insertElementAt("SUCCESS:Scholar.google可以访问", 0);
    	} else {
    		dlm.insertElementAt("FAILED:Scholar.google不能访问，请先配置好你的网络", 0);
    	}
    }                                 

    private void tryDBConnection(java.awt.event.ActionEvent evt) {
    	String username = jTextField4.getText();
    	String password = jPasswordField1.getText();
    	//System.out.println(username + " " + password);
    	int rowsfound = JDBCTester.tryDBConnection("", username, password); 
    	if (rowsfound > -1) {
            dlm.insertElementAt("SUCCESS:数据库可连通, 找到- " + rowsfound + " -条数据", 0);
    	} else {
    		dlm.insertElementAt("FAILED:数据库不可连通", 0);
    	}
    }                                

    private void startCrawlCitation(java.awt.event.ActionEvent evt) {
    	// 先测试数据连通性 和 WOS可用性
    	String username = jTextField4.getText();
    	String password = jPasswordField1.getText();
    	String woshost = jTextField1.getText();
    	String scholarhost = jTextField2.getText();
    	if(!(JDBCTester.tryDBConnection("", username, password) > -1)){
    		dlm.insertElementAt("FAILED:数据库不可连通, 请配置好数据连接再试。", 0);
    		return;
    	}
    	if (wosradiobutton.isSelected() && !ctool.tryWOS(woshost)) {
    		dlm.insertElementAt("FAILED:web of science不能访问，请先连接RVPN", 0);
    		return;
    	}
    	if (scholarradiobutton.isSelected() && !ctool.tryScholar(scholarhost)) {
    		System.out.println(scholarradiobutton.isSelected());
    		System.out.println("FAILED:Scholar.google不能访问，请先配置好你的网络");
    		dlm.insertElementAt("FAILED:scholar.google不能访问，请先配置好你的网络", 0);
    		return;
    	}
    	
    	final Thread updater = new Thread() {
		    @Override
		    public void run() {
		        Map<String, String> doi_title = mysqldao.selectTitleDOI();
		    	Set<String> key = doi_title.keySet();
		    	int i = 1;
		    	int literlen = key.size();
		    	for (Iterator it = key.iterator(); it.hasNext();) {
		    		String kk = (String) it.next();
		    		String value = doi_title.get(kk);
		    		dlm.insertElementAt("抓取第 " + i + "th/" + literlen + "个文献引用====>>[DOI:" + kk + ", Title:" + value + "]", 0);
		    		//jList1.setModel(dlm);
		            System.out.println(i + "/" + literlen + "====" + kk + " " + value);
		            if (wosradiobutton.isSelected()) {
		            	CrawlTool.getWebpageCitation(dlm, kk, value);
		            }
		            else {
		            	CrawlTool.getScholarWebpageCitation(dlm, kk, value);
		            }
		            mysqldao.update_visitedwostime(kk);
		            i++;
		            mysqldao.close();
		    	}
		    }
		};
		updater.start();
    	
//    	if (wosradiobutton.isSelected()) {
//    		final Thread updater = new Thread() {
//    		    @Override
//    		    public void run() {
//    		        Map<String, String> doi_title = mysqldao.selectTitleDOI();
//    		    	Set<String> key = doi_title.keySet();
//    		    	int i = 1;
//    		    	int literlen = key.size();
//    		    	for (Iterator it = key.iterator(); it.hasNext();) {
//    		    		String kk = (String) it.next();
//    		    		String value = doi_title.get(kk);
//    		    		dlm.insertElementAt("抓取第 " + i + "th/" + literlen + "个文献引用====>>[DOI:" + kk + ", Title:" + value + "]", 0);
//    		    		//jList1.setModel(dlm);
//    		            System.out.println(i + "/" + literlen + "====" + kk + " " + value);
//    		            CrawlTool.getWebpageCitation(dlm, kk, value);
//    		            mysqldao.update_visitedwostime(kk);
//    		            i++;
//    		            mysqldao.close();
//    		    	}
//    		    }
//    		};
//    		updater.start();
//    	} else {
//    		dlm.insertElementAt("INFO:选中Scholar开始抓取数据，但抓取Scholar没有实现", 0);
//    	}
    }                                   

    private void stopCrawlCitation(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }
    
    private void getLiterInfo(java.awt.event.ActionEvent evt) {
    		//another thread to update the model
    		final Thread updater = new Thread() {
    		    @Override
    		    public void run() {
    		        Map<String, String> doi_title = mysqldao.selectTitleDOI();
    		    	Set<String> key = doi_title.keySet();
    		    	int i = 1;
    		    	int literlen = key.size();
    		    	for (Iterator it = key.iterator(); it.hasNext();) {
    		    		String kk = (String) it.next();
    		    		String value = doi_title.get(kk);
    		    		dlm.insertElementAt(i + "/" + literlen + "====[DOI:" + kk + ", Title:" + value + "]", 0);
    		    		//jList1.setModel(dlm);
    		            i++;
    		            mysqldao.close();
    		    	}
    		    }
    		};
    		updater.start();
    }

    private void wosradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {     
    	if (wosradiobutton.isSelected()) {
    		scholarradiobutton.setSelected(false);
    	} else {
    		scholarradiobutton.setSelected(true);
    	}
    }                                              

    private void scholarradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {     
    	if (scholarradiobutton.isSelected()) {
    		wosradiobutton.setSelected(false);
    	} else {
    		wosradiobutton.setSelected(true);
    	}
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dbhost;
    private javax.swing.JLabel dbpassword;
    private javax.swing.JLabel dbusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JList jList1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel scholarhost;
    private javax.swing.JRadioButton scholarradiobutton;
    private javax.swing.JLabel woshost;
    private javax.swing.JRadioButton wosradiobutton;
    // End of variables declaration                      
}
